title: DTU Chipday
event_date: "2026-04-14T12:00:00+02:00"
event_date_display: "14 April 2026"
event_year: 2026
venue: "Glassalen, DTU Building 101"
map_lat: 55.786
map_lng: 12.524
map_zoom: 16
contact_email: jkj@icworks.dk
